version: "3"
services:
  server:
    container_name: server
    build:
      context: .
    working_dir: /var/www/myproject
    ports:
      - "$PORT:$PORT"
    volumes:
      - ./:/var/www/myproject
    command: python3 manage.py runserver 0.0.0.0:$PORT
    env_file:
      - .env
